# Generated by Django 2.1.2 on 2018-10-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='guest',
            name='address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RemoveField(
            model_name='guest',
            name='party',
        ),
        migrations.AddField(
            model_name='guest',
            name='party',
            field=models.ManyToManyField(to='rsvp.Party'),
        ),
    ]
