# Generated by Django 2.1.2 on 2018-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_auto_20181020_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
    ]
